# load packages ----
library(shiny)
library(ggplot2)
library(tidyverse)
library(sysfonts)
library(plotly)
library(dplyr)
library(leaflet)
library(DT)
library(shinythemes)

land_price <- readRDS("all_data_avg_price.rds")
land_price_data <- readRDS("all_data_avg_price_data.rds")
land_location <- readRDS("all_data_locations.rds")

# user interface ----
ui <- fluidPage(
  #theme = bslib::bs_theme(bootswatch = "cerulean"),
  theme = shinytheme("sandstone"),
  navbarPage(
    h4("Exploring land prices in Nairobi\nand its satellite towns"),
     tabPanel(h4("Introduction"),
              h3(strong("Project Description")),
              p(h4("The purpose of this Shiny App is to present land price information for Nairobi and its satellite towns.  The first two tabs demonstrate a line plot of land prices from 2015 to the present and a map to show the general location of the land. Additionally, the final section provides a data table that allows users to explore and compare land price data by quarter, year, and location.")),
              h3(strong("Data Source")),
              tags$a(href="https://www.hassconsult.com/hassindex/", "HassConsult Website"),
              p(h4("The HassConsult Land Index is a quarterly publication, generated by HassConsult Limited, that provides multiple stakeholders with current and historical information related to land prices (*Price values are rounded to nearest Kshs. 100,000). HassConsult Limited, headquartered in Nairobi, has been in operation since 1992 and engages in all aspects of real estate development."))
              ),
     tabPanel(h4("Suburbs"),
              tabsetPanel(
                tabPanel("Change in Land Prices and Map of Location",
                        fluidRow(# Location Input ----
                        column(width = 2, checkboxGroupInput(inputId = "location_choice_1", label = "Choose a location(s):",
                                    choices = c("Donholm", "Gigiri", "Karen", "Kileleshwa", "Kilimani", "Kitisuru",     
                                                "Langata", "Lavington", "Loresho", "Muthaiga", "Nyari", "Parklands",    
                                                "Ridgeways", "Riverside", "Runda", "Spring Valley", "Upperhill", 
                                                "Westlands", "Eastleigh"),
                                    selected = "Donholm")),
                      # Location and price output ----
                      column(h3("The change in land prices between 2015 and the present"),
                             h5("*[Q1 = .00, Q2 = .25, Q3 = .50, and Q4 = .75]"),
                             width = 10, plotlyOutput(outputId = "landprice_linePlot_1"),
                             h3("A map of the selected locations"),
                             leafletOutput("map_1")))))),
     tabPanel(h4("Satellite Towns"),
              tabsetPanel(
                tabPanel("Change in Land Prices and Map of Location",
                        fluidRow(# Location Input ----
                        column(width = 2, checkboxGroupInput(inputId = "location_choice_2", label = "Choose a location(s):",
                                    choices = c("Athi River", "Juja", "Kiambu", "Kiserian",     
                                                "Kitengela", "Limuru", "Mlolongo", "Ngong", "Ongata Rongai",    
                                                "Ruaka", "Ruiru", "Syokimau", "Thika", "Tigoni"),
                                    selected = "Athi River")),
                        # Location, price, and location output ----
                        column(h3("The change in land prices between 2015 and the present"),
                               h5("*[Q1 = .00, Q2 = .25, Q3 = .50, and Q4 = .75]"),
                               width = 10, plotlyOutput(outputId = "landprice_linePlot_2"),
                               h3("A map of the selected locations"),
                               leafletOutput("map_2")))))),
     tabPanel(h4("Explore the data"),
              tabsetPanel(
                tabPanel("Location, Year, Quarter, and Price Data",
                         fluidRow(# Year Input ----
                                  column(width = 2, selectInput("year", "Filter by Year:", choices = unique(land_price_data$Year), multiple = TRUE, selected = 2015),
                                                    selectInput("quarter", "Filter by Quarter:", choices = unique(land_price_data$Quarter), multiple = TRUE, selected = 1)),
                         # location/price data table output
                                  column(width = 10, DT::dataTableOutput(outputId = "landprice_table"))))
)
)
)
)

# server instructions ----
server <- function(input, output) {
 
   # filter locations ----  
  location_df_1 <- reactive({ 
    land_price %>% 
      filter(location %in% input$location_choice_1) 
    
  })
  
  location_df_2 <- reactive({ 
    land_price %>% 
      filter(location %in% input$location_choice_2) 
    
  })
  
  # render the plot ----
  
  output$landprice_linePlot_1 <- renderPlotly({ 
    plot_1 <- ggplot(na.omit(location_df_1()), 
                     aes(quarter_year, 
                         average_price,
                         color = location,
                         group = location,
                         text = paste0("Year: ", quart_year_label,
                                       "<br>Location: ", location,
                                       "<br>Avg Price: KShs ", scales::comma(average_price))
                         )) +
      geom_line(linewidth = 0.625) +
      geom_point(size = 1.25) +
      theme_classic() + 
      scale_y_continuous(labels = scales::comma) +
      scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
      labs(x = "Year",
           y = "Average Price (KShs)",
           color = "Location") +
      theme(legend.position="bottom",
            legend.title = element_text(size = 12),
            legend.text = element_text(size = 12),
            legend.background = element_rect(fill = "white"),
            panel.grid.major.x=element_blank(),
            panel.grid.minor.x=element_blank(),
            panel.grid.minor.y=element_blank(),
            axis.text.x = element_text(size = 12, angle = 45),
            axis.text.y = element_text(size = 12),
            axis.title.x = element_text(size = 15),
            axis.title.y = element_text(size = 15),
            plot.title = element_text(size = 18, face = "bold"),
            plot.subtitle = element_text(size = 18),
            plot.background = element_rect(fill = "white", color = "white"),
            panel.background = element_rect(fill = "white", color = "white"))
    
    ggplotly(plot_1, tooltip = "text")
  }) 
  
  # render the plot ----
  
  output$landprice_linePlot_2 <- renderPlotly({ 
    plot_2 <- ggplot(na.omit(location_df_2()), 
                     aes(quarter_year, 
                         average_price,
                         color = location,
                         group = location,
                         text = paste0("Year: ", quart_year_label,
                                       "<br>Location: ", location,
                                       "<br>Avg Price: KShs ", scales::comma(average_price))
                     )) +
      geom_line(linewidth = 0.625) +
      geom_point(size = 1.25) +
      theme_classic() + 
      scale_y_continuous(labels = scales::comma) +
      scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
      labs(x = "Year",
           y = "Average Price (KShs)",
           color = "Location") +
      theme(legend.position="bottom",
            legend.title = element_text(size = 12),
            legend.text = element_text(size = 12),
            legend.background = element_rect(fill = "white"),
            panel.grid.major.x=element_blank(),
            panel.grid.minor.x=element_blank(),
            panel.grid.minor.y=element_blank(),
            axis.text.x = element_text(size = 12, angle = 45),
            axis.text.y = element_text(size = 12),
            axis.title.x = element_text(size = 15),
            axis.title.y = element_text(size = 15),
            plot.title = element_text(size = 18, face = "bold"),
            plot.subtitle = element_text(size = 18),
            plot.background = element_rect(fill = "white", color = "white"),
            panel.background = element_rect(fill = "white", color = "white"))
    
    ggplotly(plot_2, tooltip = "text")
    
  }) 

  # Filter dataset based on selected location
  filtered_location_1 <- reactive({
    land_location %>% 
      filter(Location %in% input$location_choice_1)   
    })
  
  # Filter dataset based on selected location
  filtered_location_2 <- reactive({
    land_location %>% 
      filter(Location %in% input$location_choice_2)   
  })
  
  # Render the Leaflet map
  output$map_1 <- renderLeaflet({
    leaflet(data = filtered_location_1()) %>%
      addTiles() %>%
      addMarkers(
        lat = ~Latitude,
        lng = ~Longitude,
        popup = ~Location
      )
  })
  
  # Render the Leaflet map
  output$map_2 <- renderLeaflet({
    leaflet(data = filtered_location_2()) %>%
      addTiles() %>%
      addMarkers(
        lat = ~Latitude,
        lng = ~Longitude,
        popup = ~Location
      )
  })
  # render the land price data
  
  output$landprice_table <- DT::renderDataTable({

    filtered_land_price_data <-
      land_price_data %>%
      filter(Year %in% input$year & Quarter %in% input$quarter)

    datatable(filtered_land_price_data,
              options = list(pageLength = 10),
              caption = tags$caption(
                style = 'caption-side: top; text-align: left;',
                'Table 1: ', tags$em('Location, Year/Quarter, and Price'))) %>%
      formatCurrency("Average Price (KShs)",currency = "", interval = 3, mark = ",") %>%
      formatRound("Average Price (KShs)", digits = 0)
    

  })
}

# combine UI & server into an app ----
shinyApp(ui = ui, server = server)